version: '3.4'

services:
    sqldata:
        environment:
            - SA_PASSWORD=Pass@word
            - ACCEPT_EULA=Y
        ports:
            - "5433:1433"

    webapplicationcore-api:
        ports:
            - "8048:80"
            - "44348:443"
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
            - ASPNETCORE_URLS=http://+:80
            - ConnectionString=Server=sqldata;Database=DatabaseQA;User Id=sa;Password=Pass@word

    webapplicationcore-ui:
        ports:
            - "8040:80"
            - "44340:443"
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
            - ASPNETCORE_URLS=http://+:80
            - WebApplicationAPIUrl=http://webapplicationcore-api
