version: '3.4'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
    networks:
      - webapplicationcore-network

  webapplication.core.ui:
    image: ${DOCKER_REGISTRY-}webapplicationcoreui
    build:
      context: .
      dockerfile: WebApplication.Core.UI/Dockerfile
    depends_on:
      - webapplication.core.api
    networks:
      - webapplicationcore-network

  webapplication.core.api:
    image: ${DOCKER_REGISTRY-}webapplicationcoreapi
    build:
      context: .
      dockerfile: WebApplication.Core.API/Dockerfile
    depends_on:
      - sqldata
    networks:
      - webapplicationcore-network

networks:
    webapplicationcore-network:
        driver: bridge