version: '3.4'

services:
  sqldata:
    environment:
        - SA_PASSWORD=Pass@word
        - ACCEPT_EULA=Y
    ports:
        - "5433:1433"
    volumes:
        - mssql-server-data-prod:/var/opt/mssql/data

  webapplication.core.api:
    ports:
        - "8050:80"
        - "44345:443"
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - ASPNETCORE_URLS=http://+:80
        - ConnectionString=Server=sqldata;Database=DatabaseProd;User Id=sa;Password=Pass@word

  webapplication.core.ui:
    ports:
        - "8060:80"
        - "44346:443"
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - ASPNETCORE_URLS=http://+:80
        - WebApplicationAPIUrl=http://webapplication.core.api

volumes:
  mssql-server-data-prod: