 apiVersion: v1
 kind: Service
 metadata:
   annotations:
     kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
       convert --out k8s/docker-compose.yml
     kompose.version: 1.21.0 (992df58d8)
   creationTimestamp: null
   labels:
     io.kompose.service: webapplicationcore-api
   name: webapplicationcore-api
 spec:
   ports:
   - name: "8048"
     port: 8048
     targetPort: 80
   - name: "44348"
     port: 44348
     targetPort: 443
   selector:
     io.kompose.service: webapplicationcore-api
 status:
   loadBalancer: {}