apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
        convert --out k8s/docker-compose.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: sqldata
    name: sqldata
  spec:
    ports:
    - name: "5433"
      port: 5433
      targetPort: 1433
    selector:
      io.kompose.service: sqldata
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
        convert --out k8s/docker-compose.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: webapplicationcore-api
    name: webapplicationcore-api
  spec:
    ports:
    - name: "8048"
      port: 8048
      targetPort: 80
    - name: "44348"
      port: 44348
      targetPort: 443
    selector:
      io.kompose.service: webapplicationcore-api
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
        convert --out k8s/docker-compose.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: webapplicationcore-ui
    name: webapplicationcore-ui
  spec:
    ports:
    - name: "8040"
      port: 8040
      targetPort: 80
    - name: "44340"
      port: 44340
      targetPort: 443
    selector:
      io.kompose.service: webapplicationcore-ui
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
        convert --out k8s/docker-compose.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: sqldata
    name: sqldata
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: sqldata
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
            convert --out k8s/docker-compose.yml
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: sqldata
      spec:
        containers:
        - env:
          - name: "ACCEPT_EULA"
            value: "Y"
          - name: "SA_PASSWORD"
            value: "Pass@word"
          image: mcr.microsoft.com/mssql/server:2017-latest
          imagePullPolicy: ""
          name: sqldata
          ports:
          - containerPort: 1433
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
        convert --out k8s/docker-compose.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: webapplicationcore-api
    name: webapplicationcore-api
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: webapplicationcore-api
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
            convert --out k8s/docker-compose.yml
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: webapplicationcore-api
      spec:
        containers:
        - env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ASPNETCORE_URLS
            value: http://+:80
          - name: ConnectionString
            value: "Server=sqldata,5433;Database=Database;User Id=sa;Password=Pass@word"
          image: alanmacgowan/webapplication.core.api
          imagePullPolicy: ""
          name: webapplicationcore-api
          ports:
          - containerPort: 80
          - containerPort: 443
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
        convert --out k8s/docker-compose.yml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: webapplicationcore-ui
    name: webapplicationcore-ui
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: webapplicationcore-ui
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
            convert --out k8s/docker-compose.yml
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: webapplicationcore-ui
      spec:
        containers:
        - env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ASPNETCORE_URLS
            value: http://+:80
          - name: WebApplicationAPIUrl
            value: http://webapplicationcore-api:8048
          image: alanmacgowan/webapplication.core.ui
          imagePullPolicy: ""
          name: webapplicationcore-ui
          ports:
          - containerPort: 80
          - containerPort: 443
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
kind: List
metadata: {}

