apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert --out k8s/docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: webapplicationcore-ui
  name: webapplicationcore-ui
spec:
  ports:
  - name: "8040"
    port: 8040
    targetPort: 80
  - name: "44340"
    port: 44340
    targetPort: 443
  selector:
    io.kompose.service: webapplicationcore-ui
status:
  loadBalancer: {}


