apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert --out k8s/docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: webapplicationcore-ui
  name: webapplicationcore-ui
spec:
  type: NodePort
  selector:
    io.kompose.service: webapplicationcore-ui
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
status:
  loadBalancer: {}


